---
title: "R Notebook"
output: html_notebook
---

Code for figures in main paper 

```{r}
library(tidyverse)
library(latex2exp)
# library(plotly)
source("plot_utils.R")
library(xtable) # for converting dataframes to latex

rename_methods <- function(df) {
  return(mutate(df, method = factor(recode(method,
    bc = "DR",
    conf = "TCR",
    pl = "PL"
  ),
  levels = rev(c(
    "DR",
    "PL",
    "TCR"
  ))
  )))
}
```

# correlation coefficient

```{r}
results_folder <- "results/paper/no_split/"
var_param <- quo(m)


fl <- list.files(results_folder, pattern = ".results.")
setwd(results_folder)
results <- bind_rows(lapply(fl, readRDS)) %>% rename_methods()
```



# Vary p, q, but fix gamma and zeta 

```{r}
var_param <- quo(p)
img_folder <- "img/paper/uncor/vary_p_q_"
z <- 20
alg <- "LASSO"
results %>%
   dplyr::filter(m == 0, 
                 gamma == 25,
                 algorithm == alg,
                 zeta == z) %>%
  dplyr::group_by(!! var_param, method) %>%
  dplyr::filter(! (method %in% c("Oracle DR"))) %>%
  dplyr::summarise(
    mmse = mean(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()),
  ) %>%
  ggplot(aes(x = !! var_param, y = mmse, color = method)) +
  geom_point(size = 1.5) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 10, size = 1) +
 ylab("") + 
 scale_x_continuous(breaks = seq(50, 450, 50), minor_breaks = seq(50, 450, 50)) +
 xlab(TeX("$d_v$")) +
  scale_color_manual(values = cbPalette[1:4])+
  theme_bw(base_size = 30) +
  ylim(c(3, 40)) + 
   theme(legend.position = "none", legend.title = element_blank())

ggsave(glue::glue(img_folder, "zeta{z}_{alg}.pdf"), width =8, height = 8)
```


```{r}
var_param <- quo(p)
z <- 20
alg <- "RF"
results %>%
   dplyr::filter(m == 0, 
                 gamma == 25,
                 algorithm == alg,
                 zeta == z) %>%
  dplyr::group_by(!! var_param, method) %>%
  dplyr::filter(! (method %in% c("Oracle DR"))) %>%
  dplyr::summarise(
    mmse = mean(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()),
  ) %>%
  ggplot(aes(x = !! var_param, y = mmse, color = method)) +
  geom_point(size = 1.5) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 10, size = 1) +
 ylab("") + 
 scale_x_continuous(breaks = seq(50, 450, 50), minor_breaks = seq(50, 450, 50)) +
 xlab(TeX("$d_v$")) +
  scale_color_manual(values = cbPalette[1:4])+
theme_bw(base_size = 30) +
  ylim(c(3, 40)) + 
   theme(legend.position = "none", legend.title = element_blank())

ggsave(glue::glue(img_folder, "zeta{z}_{alg}.pdf"), width =8, height = 8)
```

# Vary zeta for fixed, p, q, gamma 


> correlated LASSO

```{r}
var_param <- quo(zeta)
img_folder <- "img/paper/uncor/vary_zeta"
alg <- "LASSO"
dv <- 400
results %>%
  dplyr::filter(p == dv, 
                gamma == 25,
                algorithm == alg, 
                m == 0) %>%
  dplyr::group_by(!!var_param, method) %>%
  dplyr::summarise(
    mmse = mean(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()),
  ) %>%
  ggplot(aes(x = !!var_param, y = mmse, color = method)) +
  geom_point(size = 1.75) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 1.25, size = 1) +
 ylab("") + 
   scale_x_continuous(breaks = seq(0, 60, 5), minor_breaks = seq(0, 60, 5)) +
  xlab(TeX("$k_z$")) +
  scale_color_manual(values = cbPalette) +
theme_bw(base_size = 30) +
  ylim(c(3, 40)) + 
  theme(legend.position = "none", legend.title = element_blank())
ggsave(glue::glue(img_folder, "_p{dv}_{alg}.pdf"), width = 8, height = 8)
```

```{r}
var_param <- quo(zeta)
img_folder <- "img/paper/uncor/vary_zeta"
alg <- "RF"
dv <- 400
results %>%
  dplyr::filter(p == dv, 
                gamma == 25,
                algorithm == alg, 
                m == 0) %>%
  dplyr::group_by(!!var_param, method) %>%
  dplyr::summarise(
    mmse = mean(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()),
  ) %>%
  ggplot(aes(x = !!var_param, y = mmse, color = method)) +
  geom_point(size = 1.75) +
  geom_errorbar(aes(ymin = low, ymax = high), width = 1.25, size = 0.7) +
  #ylab(TeX("$E\\[(\\nu(V) - \\hat{\\nu}(V))^2\\]$")) +
  ylab("") + 
   scale_x_continuous(breaks = seq(0, 60, 5), minor_breaks = seq(0, 60, 5)) +
  xlab(TeX("$k_z$")) +
  scale_color_manual(values = cbPalette) +
theme_bw(base_size = 30) +
  ylim(c(3, 40)) + 
  theme(legend.position = "none", legend.title = element_blank())
ggsave(glue::glue(img_folder, "_p{dv}_{alg}.pdf"), width = 8, height = 8)
```