---
title: "Visualization Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
source("regression_functions.R")
source("utils.R")
```

```{r}
# n_sim <- 10
prop_cutoff <- 1
sd_v1 <- 10
c <- 0.4

# create a test set to be used for all simulations
v <- seq(-30, 30, .01)
test <- tibble(
  v1 = v,
  nu = compute_nu(v, c)
)

n_test <- nrow(test)

fl <- list.files("results/prop100/plugin/")
setwd("results/prop100/plugin/")
res <- dplyr::bind_rows(lapply(fl, readRDS))

res %>%
  dplyr::filter(sim_num != 11) %>%
  dplyr::group_by(eps_n_exp, eps_sd, method, nu, v1) %>%
  dplyr::summarise(variance = var(pred),
                   bias = mean(pred) - mean(nu),
                   pred = mean(pred)
                   ) -> res_agg

total_w <- sum(dnorm(test$v1, mean = 0, sd = sd_v1))
res_agg %>% 
  dplyr::mutate(sqerr = bias^2 + variance,
    w = dnorm(v1, mean = 0, sd = sd_v1)/total_w) -> res_agg

res_agg %>% 
  dplyr::ungroup() %>%
  dplyr::group_by(eps_n_exp, eps_sd, method) %>%
  dplyr::summarise(mse = sum(w*sqerr),
                vse = n_test * var(w*sqerr)) %>%
  dplyr::mutate(low = mse - 1.96 *sqrt(vse),
                high = mse + 1.96 *sqrt(vse)
                )-> res_sum
```

```{r}
res_agg %>% 
  dplyr::filter(method == "const", eps_n_exp == 0, eps_sd == 0) %>%
  ggplot(aes(x = v1, y = sqerr)) + geom_point()
```


```{r}
res_agg %>% 
  dplyr::group_by(method, eps_n_exp, eps_sd) %>%
  summarise(min_sqerr = min(sqerr),
            max_sqerr = max(sqerr),
            median_sqerr = median(sqerr),
            unweight_sqerr = mean(sqerr))
```


```{r}
res_agg %>% 
  dplyr::filter(method == "pl", eps_sd == 1, eps_n_exp == .25) %>% 
  dplyr::pull(w) %>% sum()
```

```{r}
res_sum %>%
  dplyr::filter(method == "pl") %>%
    ggplot(aes(x=eps_n_exp, y= mse, color = method, fill = method))  +
  geom_ribbon(aes(ymin=low, ymax=high), alpha = 0.4) + 
  geom_point() + 
  ylab('Mean Squared Error') + 
  facet_grid(eps_sd ~.)  + 
  theme_grey(base_size=12)    + theme(legend.position = "bottom") 

```

```{r}
res_sum %>%
    ggplot(aes(x=eps_sd, y= mse, color = method, fill = method))  + geom_ribbon(aes(ymin=low, ymax=high), alpha = 0.4)+ geom_point()+ ylab('Mean Squared Error') + facet_grid(eps_n_exp ~.)  + theme_grey(base_size=12)    + theme(legend.position = "bottom") 

```

```{r}
res_agg %>%
  dplyr::filter(eps_sd == 10, eps_n_exp == .1) %>%
   ggplot(aes(x = nu, y = pred, color = method, fill = method)) + geom_point()+ geom_abline(slope= 1, intercept = 0)  + facet_grid(eps_sd ~.)  + theme_grey(base_size=12)    + theme(legend.position = "bottom") 
```

```{r}
res_agg %>%
   ggplot(aes(x = nu, y = pred, color = method, fill = method)) +
  geom_point()+
  geom_abline(slope= 1, intercept = 0)  +
  facet_grid(eps_sd ~ eps_n_exp)  + 
  theme_grey(base_size=12)  + theme(legend.position = "bottom") 
```

```{r}
res_agg %>%
  dplyr::filter(eps_sd == .5, method != "conf") %>%
   ggplot(aes(x = v1, y = bias^2, color = method, fill = method)) + geom_point()+ ylab('Bias Sq') + facet_grid(eps_n_exp ~.)  + theme_grey(base_size=12)    + theme(legend.position = "bottom") 

```

```{r}
res_agg %>%
  dplyr::filter(eps_sd == .1, eps_n_exp == .25) %>%
   ggplot(aes(x=v1, y= variance, color = method, fill = method)) + geom_point()+ ylab('Variance') + facet_grid(eps_sd ~.)  + theme_grey(base_size=12)    + theme(legend.position = "bottom") 

```

```{r}
res_agg %>%
  dplyr::filter(eps_sd == .1, eps_n_exp == .25) %>%
   ggplot(aes(x=v1, y= sqerr, color = method, fill = method)) + geom_point()+ ylab('Squared Error') + facet_grid(eps_sd ~.)  + theme_grey(base_size=12)    + theme(legend.position = "bottom") 

```

> Performance at the mean

```{r}
res_agg %>%
  dplyr::filter(v1 == 0, eps_sd < 5) %>% 
   ggplot(aes(x=eps_n_exp, y= sqerr, color = method, fill = method)) + geom_point()+ ylab('Mean Squared Error') + facet_grid(eps_sd ~.) +ylim(c(0, 0.0075)) + theme_grey(base_size=12)    + theme(legend.position = "bottom") 

```

