---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
```


This notebook visualizes the simulation results in 
```{r}
#results_folder <- "results/highdim/misspec/"
#results_folder <- "results/highdim/expected_with_more_oracles/"

#results_folder <- "results/highdim/binary5/"  # plugin achieves pl oracle
#results_folder <- "results/highdim/alpha40_q35/" # RT for comparison

#results_folder <- "results/highdim/binary_small_coef2/" # Edward's setup with less sparsity
#results_folder <- "results/highdim/binary9/" # Edward's setup with less sparsity


#results_folder <- "results/highdim/binary_small_coef/" # Edward's setup: low error across the board including confounded
#results_folder <- "results/highdim/binaryk/k3" 

#results_folder <- "results/highdim/easyMU_LRsecond2/" # with no hidden confounding plugin struggles in second stage
#results_folder <- "results/highdim/alpha40_q35/" # RT for comparison
#results_folder <- "results/highdim/misspec/"


#results_folder <- "results/highdim/binary3/" # shows differences
#results_folder <- "results/highdim/binary/" 
#results_folder <- "results/highdim/regression/expected/" 
results_folder <- "results/highdim/binary/miss_prop_widen/" 
#results_folder <- "results/highdim/binary/prop_widen" 



results <- readRDS(glue::glue(results_folder,"results.Rds"))
parameters <- readRDS(glue::glue(results_folder, "parameters.Rds"))

```

```{r}
parameters
```

```{r}
results %>%
  dplyr::group_by(method) %>%
  dplyr::summarise(
    mmse = mean(mse),
    count = n(),
    vmse = var(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()), 
  ) 
```
```{r}
parameters
```
```{r}
summary(results)
```


```{r fig.width=15, fig.height=8}
results %>%
  dplyr::mutate(method = factor(recode(results$method,
                                bc = "DR",
                                bct = "Oracle DR",
                                conf = "BTR",
                                pl = "PL"),
                levels = rev(c(
                  "bc_true_prop",
                  "bc_true_mu",
                  "bc_rt_true_mu",
                  "bc_rt_muest",
                  "conf1se",
                  "pl1se",
                  "regression_diff",
                  "Oracle DR",
                           "DR",
                           "PL",
                           "BTR"))))-> results
results %>%
  dplyr::group_by(method) %>%
  dplyr::filter(!(method %in% c("bc_true_prop",
                  "bc_true_mu",
                  "bc_rt_true_mu",
                  "bc_rt_muest",
                  "conf1se",
                  "pl1se",
                  "regression_diff"))) %>%
  dplyr::summarise(
    mmse = mean(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()), 
  ) %>%
  ggplot(aes(x = method, y = mmse, color = method)) +
  geom_point() +
  geom_errorbar(aes(ymin = low, ymax = high)) +
  theme_bw(base_size = 15) +
  theme(legend.position = "bottom") +
  ylab("Mean Squared Error")
#ggsave("img/binary_misspec_prop_widen.pdf", width = 15, height = 8)
```

# bar plot

```{r fig.width=6, fig.height=6}
results %>%
  dplyr::mutate(method = factor(recode(results$method,
                                bc = "DR",
                                bct = "Oracle DR",
                                conf = "BTR",
                                pl = "PL"),
                levels = rev(c(
                  "bc_true_prop",
                  "bc_true_mu",
                  "bc_rt_true_mu",
                  "bc_rt_muest",
                  "conf1se",
                  "pl1se",
                  "regression_diff",
                  "Oracle DR",
                           "DR",
                           "PL",
                           "BTR"))))-> results
results %>%
  dplyr::group_by(method) %>%
  dplyr::filter(!(method %in% c("bc_true_prop",
                  "bc_true_mu",
                  "bc_rt_true_mu",
                  "bc_rt_muest",
                  "conf1se",
                  "pl1se",
                  "regression_diff"))) %>%
  dplyr::summarise(
    mmse = mean(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()), 
  ) %>%
  ggplot(aes(x = method, y = mmse, color = method, fill = method)) +
  geom_col() +
  geom_errorbar(aes(ymin = low, ymax = high), color = "black") +
  theme_bw(base_size = 15) +
  theme(legend.position = "none") +
  ylab("Mean Squared Error")
#ggsave("img/binary_misspec_prop_widen.pdf", width = 6, height = 6)
```

todo: violin
```{r}
# results %>%
#   dplyr::group_by(method) %>%
#   dplyr::filter(!(method %in% c("pl1se", "conf1se", "Oracle PL 1 se", "oracle_plugin_1se", "regression_diff", "oracle_plugin"))) %>%
#   dplyr::summarise(
#     mmse = mean(mse),
#     low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
#     high = mean(mse) + 1.96 * sqrt(var(mse) / n()), 
#   ) %>%
#   ggplot(aes(x = method, y = mmse, color = method)) +
#   geom_point() +
#   geom_errorbar(aes(ymin = low, ymax = high)) +
#   theme_bw(base_size = 15) +
#   theme(legend.position = "bottom") +
#   ylab("Mean Squared Error")
# #ggsave("img/binary_small_coef2.pdf", width = 15, height = 8)
```