---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
```


This notebook visualizes the simulation results  that vary dim_z

```{r}
results <- readRDS(glue::glue("results/highdim/expected/","results.Rds"))
parameters <- readRDS(glue::glue("results/highdim/expected/", "parameters.Rds"))

results %>% 
  dplyr::mutate(q = parameters$dim_z) -> results1

results <- readRDS(glue::glue("results/highdim/dim_z_10/","results.Rds"))
parameters <- readRDS(glue::glue("results/highdim/dim_z_10/", "parameters.Rds"))

results %>% 
  dplyr::mutate(q = parameters$dim_z) -> results0

results <- readRDS(glue::glue("results/highdim/dim_z_30/","results.Rds"))
parameters <- readRDS(glue::glue("results/highdim/dim_z_30/", "parameters.Rds"))

results %>% 
  dplyr::mutate(q = parameters$dim_z) -> results30

results <- readRDS(glue::glue("results/highdim/q35/","results.Rds"))
parameters <- readRDS(glue::glue("results/highdim/q35/", "parameters.Rds"))

results %>% 
  dplyr::mutate(q = parameters$dim_z) -> results35

results <- readRDS(glue::glue("results/highdim/q1/","results.Rds"))
parameters <- readRDS(glue::glue("results/highdim/q1/", "parameters.Rds"))

results %>% 
  dplyr::mutate(q = parameters$dim_z) -> resultsz1

results <- bind_rows(results0, results1, results30, results35, resultsz1)
```

```{r}
results %>%
  dplyr::group_by(q, method) %>%
  dplyr::summarise(
    mmse = mean(mse),
    count = n(),
    vmse = var(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()), 
  ) 
```

```{r}
parameters
```

Note that we have set zeta = q.
We predict that at a low zeta, the confounded model will do reasonably well.
As we increase zeta, we expect this model to do worse.
Also,  as we decrease p (which is achieved by increasing q), we expect the plugin to do better. 
We see expected results.
```{r}
results %>%
  dplyr::mutate(method = factor(recode(results$method, 
                                bc = "BC",
                                bct = "Oracle BC",
                                conf = "BTR", 
                                pl = "PL"), 
                levels = rev(c("Oracle BC",
                           "pl1se", 
                           "conf1se",
                           "BC",
                           "PL", 
                           "BTR"))))-> results
results %>%
  dplyr::group_by(q, method) %>%
  dplyr::filter(!(method %in% c("pl1se", "conf1se"))) %>%
  dplyr::summarise(
    mmse = mean(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()), 
  ) %>%
  ggplot(aes(x = q, y = mmse, color = method)) +
  geom_point() +
  geom_errorbar(aes(ymin = low, ymax = high), width = 0.5) +
  ylab("Mean Squared Error") + 
  scale_x_continuous(breaks = c(10, 20, 30), minor_breaks = c(10, 20, 30)) +
 #xlab("q (dimensionality of confounding variable Z)") +
  theme_bw(base_size = 15)  
  #theme(legend.position = "bottom")
#ggsave("img/mse_varyq.pdf")
```

```{r}
results %>%
  dplyr::group_by(q, method) %>%
  dplyr::filter(!(method %in% c("pl1se", "conf1se"))) %>%
  dplyr::summarise(
    mmse = mean(mse),
    low = mean(mse) - 1.96 * sqrt(var(mse) / n()),
    high = mean(mse) + 1.96 * sqrt(var(mse) / n()), 
  ) %>%
  ggplot(aes(x = method, y = mmse, color = method, fill = method)) +
  geom_col() +
  geom_errorbar(aes(ymin = low, ymax = high)) +
  ylab("Mean Squared Error") + 
  facet_grid(q ~., scales = "free_y")
  theme_bw(base_size = 15)
#ggsave("img/mse.pdf")
```